In [81]:
import numpy as np

r1=int(input("No of elements in row1:"))
c1=int(input("No of elements in coloumn1:"))
array1=np.zeros([r1,c1],dtype=int)
for i in range(r1):
    for j in range(c1):
        array1[i,j]=int(input("Enter element:"))
        
r2=int(input("No of elements in row2:"))
c2=int(input("No of elements in coloumn2:"))
array2=np.zeros([r2,c2],dtype=int)
for i in range(r2):
    for j in range(c2):
        array2[i,j]=int(input("Enter element:"))

print("Arrays:")
print(array1)
print(array2)

#SUM
print(f'Sum of arrays is {np.add(array1,array2)}')
print(f'Sum of arrays is {array1+array2}')
#PRODUCT
print(f'Product of arrays is {np.dot(array1,array2)}')
print(f'Product of arrays is {array1@array2}')
#TRANSPOSE
print(f'Transpose of array1 is {np.transpose(array1)}')
print(f'Transpose of array2 is {np.transpose(array2)}')


No of elements in row1: 2
No of elements in coloumn1: 2
Enter element: 1
Enter element: 2
Enter element: 3
Enter element: 4
No of elements in row2: 2
No of elements in coloumn2: 2
Enter element: 5
Enter element: 6
Enter element: 7
Enter element: 8


Arrays:
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Sum of arrays is [[ 6  8]
 [10 12]]
Sum of arrays is [[ 6  8]
 [10 12]]
Product of arrays is [[19 22]
 [43 50]]
Product of arrays is [[19 22]
 [43 50]]
Transpose of array1 is [[1 3]
 [2 4]]
Transpose of array2 is [[5 7]
 [6 8]]


In [100]:
#LINEAR SEARCH in array

def KeySearch(array,k):
     j = "Key %d is not found"%k 
     for i in range(len(array)):
        if array[i]==k:
            l ="Key %d is found at index %d"%(k,i)  
            return l
     return j

a = np.array([1, 2, 4])  
print("Array is ", a)  
m = KeySearch(a, 2)  
n = KeySearch(a, 6)  
print(m)  
print(n) 



Array is  [1 2 4]
Key 2 is found at index 1
Key 6 is not found


In [101]:
# BINARY SEARCH in array
def Search(a, key, l, r):  
    mid = l + r // 2      
    if r >= l:          
        if (key == a[mid]):  
            return "Key %d is found at index %d"%(key, mid)          
    elif (key >= a[mid]):  
        return Search(a, key, mid+l, r)          
    elif (key < a[mid]):  
        return Search(a, key, l, mid)  
    return "Key %d is not Found"%key   
    
# array should always be SORTED for BINARY SEARCH  
a = np.array([1, 6, 4, 2, 0, 4, 9, 5, 56, 53])  
a.sort() # or 
np.sort(a)  
print(a)  
print(type(a))  
print(Search(a, 70, 0, len(a)-1))  
print(Search(a, 4, 0, len(a)-1))  

[ 0  1  2  4  4  5  6  9 53 56]
<class 'numpy.ndarray'>
Key 70 is not Found
Key 4 is found at index 4


In [85]:
# NUMPY
      # NumPy is a Python library used for working with arrays.

import numpy

#ARRAYS
    # The array object in NumPy is called ndarray
import numpy as np 

# 0-D arrays (scalars) - are the elements in an array. Each value in an array is a 0-D array. 
arr = np.array(42) 
print(arr) 
print()

#  1-D Arrays - An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array. These are the most common and basic arrays. 
arr = np.array([1, 2, 3, 4, 5]) 
print(arr) 
print()

# 2-D Arrays (Matrix or table) - An array that has 1-D arrays as its elements is called a 2-D array. . 
    #NumPy has a whole sub module dedicated towards matrix operations called numpy.mat  
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr)
print()

# 3-D arrays - An array that has 2-D arrays (matrices) as its elements is called 3-D array. 
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) 
print(arr)
print()

# DIMENSIONS - NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have. 
a = np.array(42) 
b = np.array([1, 2, 3, 4, 5]) 
c = np.array([[1, 2, 3], [4, 5, 6]]) 
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) 
print(a.ndim) 
print(b.ndim) 
print(c.ndim) 
print(d.ndim)

42

[1 2 3 4 5]

[[1 2 3]
 [4 5 6]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

0
1
2
3


In [77]:
# SLICING arrays 
  #Slicing in python means taking elements from one given index to another given index. 

# STEP - Use the step value to determine the step of the slicing:
arr = np.array([1, 2, 3, 4, 5, 6, 7])  
print(arr[1:5:2]) 

# Negative Slicing - Use the minus operator to refer to an index from the end
arr = np.array([1, 2, 3, 4, 5, 6, 7]) 
print(arr[-3:-1])


#Slicing 2D array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]) 
print(arr[1, 1:4])

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]) 
print(arr[0:2, 2])

#Slicing 3D array
arr = np.array([[[1, 2], [4, 5]], [[7, 8], [10, 11]]])
arr[0:1,0:2]

[2 4]
[5 6]
[7 8 9]
[7 8 9]
[3 8]


array([[[1, 2],
        [4, 5]]])

In [21]:
#RESHAPING
  # Reshaping means changing the shape of an array. 
  # The shape of an array is the number of elements in each dimension. 
  # By reshaping we can add or remove dimensions or change number of elements in each dimension. 


#1D to 2D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) 
newarr = arr.reshape(4, 3) 
print(newarr) 

print('-------')

#1D to 3D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2,3,2)   #2 arrays that contains 3 arrays, each with 2 elements
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
-------
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [52]:
#FLATTENING
# Flattening array means converting a multidimensional array into a 1D array.

arr_3D = np.array([[[ 1,2],[ 3,4],[ 5,6]],[[ 7,8],[ 9,10],[11,12]]]) 
newarr = arr_3D.reshape(-1) 
print(newarr) 

arr_2D = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr_2D.reshape(-1) 
print(newarr) 



[ 1  2  3  4  5  6  7  8  9 10 11 12]
[1 2 3 4 5 6]


In [53]:
#SPLIT Into Arrays 
   # The return value of the array_split() method is an array containing each of the split as an array. 
   # If you split an array into 3 arrays, you can access them from the result just like any array element: 

arr = np.array([1, 2, 3, 4, 5, 6]) 
newarr=np.array_split(arr,3)
print(newarr)

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr=np.array_split(arr,3)
print(newarr[2])

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]]) 
newarr = np.array_split(arr, 3) 
print(newarr[1]) 

#can specify which axis you want to do the split around.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]]) 
newarr = np.array_split(arr, 3, axis=1) 
print(newarr)

#hsplit() - opposite f hstack()
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]]) 
newarr = np.hsplit(arr, 3) 
print(newarr[2]) 

[array([1, 2]), array([3, 4]), array([5, 6])]
[[ 9 10]
 [11 12]]
[[ 7  8  9]
 [10 11 12]]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [56]:
# SEARCHING arrays - np.where(condition)

arr = np.array([1, 2, 3, 4, 5, 4, 4]) 
x=np.where(arr==4)
print(x)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) 
x = np.where(arr%2 == 0)   #where value is even number
print(x)

(array([3, 5, 6], dtype=int64),)
(array([1, 3, 5, 7], dtype=int64),)


In [63]:
#SEARCHSORTED - np.searchsorted(array,value)
 #There is a method called searchsorted() which performs a binary search in the array, 
 #and returns the index where the specified value would be inserted to maintain the search order.

arr = np.array([6, 7, 8, 9]) 
x = np.searchsorted(arr, 7) 
print(x)

arr = np.array([6, 7, 8, 9]) 
x = np.searchsorted(arr, 7, side='right')   
#By default the left most index is returned, but we can give side='right' to return the right most index instead. 
print(x) 

arr = np.array([1, 3, 5, 7]) 
x = np.searchsorted(arr, [1, 7, 5])   #search multiple values by putting them in an array
print(x)

arr = np.array([1, 3, 5, 7]) 
x = np.searchsorted(arr, [4, 2, 6, 8])   #find the indexes where the values 2, 4, and 6 should be inserted
print(x)

1
2
[0 3 2]
[2 1 3 4]


In [74]:
# SORTING arrays - np.sort()

#Sorting means putting elements in an ordered sequence. 
   # Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending. 

arr = np.array([3, 2, 0, 1]) 
print(np.sort(arr))

arr = np.array(['banana', 'cherry', 'apple']) 
print(np.sort(arr))

#sort 2D array  (both arrays will be sorted)
arr = np.array([[3, 2, 4], [5, 0, 1]]) 
print(np.sort(arr))

[0 1 2 3]
['apple' 'banana' 'cherry']
[[2 3 4]
 [0 1 5]]
